/* eslint-disable @typescript-eslint/no-var-requires -- Expo config plugins run as plain CommonJS under Node, outside the app's TS/babel pipeline */
const { withAppDelegate } = require('@expo/config-plugins');

/**
 * Under the classic (non-scene) lifecycle, a deep link -- the
 * exp+wordquest:// scheme the dev-client uses to tell this app which Metro
 * server to connect to, plus wordquest:// / universal links -- arrives via
 * -application:openURL:options: and
 * -application:continueUserActivity:restorationHandler: (both already
 * implemented in AppDelegate.mm). Once UIScene lifecycle is enforced (see
 * withSceneDelegateWindow), the OS instead delivers those to the *scene*
 * delegate's -scene:openURLContexts: and -scene:continueUserActivity: --
 * those app-level methods simply stop being called for a URL/activity that
 * arrives while the app launches or resumes via one. Without this, the
 * dev-client never receives the Metro server address from a scanned QR
 * code or a "Reload" deep link, no matter how many times you scan it.
 *
 * Adds -scene:openURLContexts: and -scene:continueUserActivity: to
 * AppDelegate.mm, routing both back through the existing app-level methods
 * (rather than duplicating their logic) so every handler chain -- Expo's
 * module dispatch via super, and RCTLinkingManager -- still runs exactly
 * as before.
 *
 * Runs on every prebuild (clean or not), matching the other local plugins.
 */
module.exports = function withSceneURLHandling(config) {
  return withAppDelegate(config, (config) => {
    const marker = '// @generated by withSceneURLHandling (do not edit by hand)';
    if (config.modResults.contents.includes(marker)) {
      return config;
    }

    const anchor = '// Linking API';
    if (!config.modResults.contents.includes(anchor)) {
      throw new Error(
        "withSceneURLHandling: could not find the '// Linking API' anchor in AppDelegate.mm to splice into -- Expo's AppDelegate template may have changed.",
      );
    }

    const snippet = `${marker}
// Under the classic (non-scene) lifecycle, a deep link (the exp+wordquest://
// scheme the dev-client uses to tell this app which Metro server to connect
// to, plus any of our own wordquest:// / universal links) arrives via
// -application:openURL:options: below and -application:continueUserActivity:
// restorationHandler:, both already implemented. Once UIScene lifecycle is
// enforced, the OS instead delivers those to the *scene* delegate's
// -scene:openURLContexts: and -scene:continueUserActivity: -- the app-level
// methods below simply stop being called for a URL/activity that arrives
// while the app launches or resumes via one. Route both back through the
// existing methods (rather than duplicating their logic) so every handler
// chain -- Expo's module dispatch via super, and RCTLinkingManager -- still
// runs exactly as before.
- (void)scene:(UIScene *)scene openURLContexts:(NSSet<UIOpenURLContext *> *)URLContexts
{
  for (UIOpenURLContext *context in URLContexts) {
    NSMutableDictionary<UIApplicationOpenURLOptionsKey, id> *options = [NSMutableDictionary dictionary];
    if (context.options.sourceApplication) {
      options[UIApplicationOpenURLOptionsSourceApplicationKey] = context.options.sourceApplication;
    }
    if (context.options.annotation) {
      options[UIApplicationOpenURLOptionsAnnotationKey] = context.options.annotation;
    }
    options[UIApplicationOpenURLOptionsOpenInPlaceKey] = @(context.options.openInPlace);
    [self application:[UIApplication sharedApplication] openURL:context.URL options:options];
  }
}

- (void)scene:(UIScene *)scene continueUserActivity:(NSUserActivity *)userActivity
{
  [self application:[UIApplication sharedApplication]
      continueUserActivity:userActivity
         restorationHandler:^(NSArray<id<UIUserActivityRestoring>> *_Nullable restorableObjects) {
         }];
}

`;

    config.modResults.contents = config.modResults.contents.replace(anchor, snippet + anchor);
    return config;
  });
};
