/* eslint-disable @typescript-eslint/no-var-requires -- Expo config plugins run as plain CommonJS under Node, outside the app's TS/babel pipeline */
const { withAppDelegate } = require('@expo/config-plugins');

/**
 * RCTAppDelegate's own -application:didFinishLaunchingWithOptions: creates
 * self.window with -initWithFrame: before any UIScene exists -- it predates
 * React Native's scene support being mandatory. Xcode 27 / iOS 27 enforce
 * UIScene adoption as a hard launch requirement (see withPodDeploymentTarget
 * / the ios.infoPlist UIApplicationSceneManifest entry in app.json, which
 * point AppDelegate at itself as the scene delegate -- RCTAppDelegate
 * already formally conforms to UISceneDelegate). Declaring the scene
 * delegate alone is enough to stop the launch-time crash, but a window
 * created via -initWithFrame: never actually gets composited once scenes
 * are enforced, and UIWindow.windowScene is read-only so it can't just be
 * attached after the fact -- the result is a real, running app showing a
 * blank black screen.
 *
 * This adds -scene:willConnectToSession:options: to AppDelegate.mm, which
 * re-hosts the same rootViewController RN's own bootstrapping already built
 * into a new window that IS properly attached via -initWithWindowScene:.
 * Nothing about RN's own setup changes -- this only re-parents the
 * already-built root view controller once the scene becomes available.
 *
 * IMPORTANT: `self` inside -scene:willConnectToSession:options: is NOT the
 * same object as the UIApplicationDelegate singleton that
 * -application:didFinishLaunchingWithOptions: ran on. UIKit always
 * allocates a separate instance for scene-delegate duties, even when
 * UISceneDelegateClassName names this very class -- so self.window in this
 * method is a distinct, always-nil ivar, on every launch, no exceptions.
 * The already-built window/rootViewController has to be read off
 * [UIApplication sharedApplication].delegate instead, and the new
 * scene-attached window written back onto that singleton's own `window`
 * property too, since plain UIApplicationDelegate callbacks (openURL,
 * remote notifications, etc.) keep running on the singleton and reference
 * *its* self.window.
 *
 * It also forwards any URL/user-activity the OS hands to this method via
 * connectionOptions -- this is how a COLD launch (app not already running)
 * delivers a URL, such as the dev-client's exp+wordquest:// deep link that
 * tells this app which Metro server to use. -scene:openURLContexts: (added
 * by withSceneURLHandling) only fires for a URL that arrives while the app
 * is already running; without this, every cold-started QR scan silently
 * drops its URL and RCTBundleURLProvider falls back to its localhost
 * default, which is invisible on a physical device.
 *
 * Runs on every prebuild (clean or not), matching withPodDeploymentTarget.
 */
module.exports = function withSceneDelegateWindow(config) {
  return withAppDelegate(config, (config) => {
    const marker = '// @generated by withSceneDelegateWindow (do not edit by hand)';
    if (config.modResults.contents.includes(marker)) {
      return config;
    }

    const anchor = '- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge';
    if (!config.modResults.contents.includes(anchor)) {
      throw new Error(
        "withSceneDelegateWindow: could not find the anchor method in AppDelegate.mm to splice into -- Expo's AppDelegate template may have changed.",
      );
    }

    const snippet = `${marker}
// RCTAppDelegate's own -application:didFinishLaunchingWithOptions: (called
// via super, above) creates self.window with -initWithFrame: before any
// UIScene exists -- it predates React Native's scene support being
// mandatory. Now that Xcode 27 / iOS 27 enforce UIScene adoption, a window
// created that way never actually gets composited on screen, and
// UIWindow.windowScene is read-only so it can't just be attached after the
// fact. Once the scene connects, re-host the same rootViewController (built
// by RN's own bootstrapping above) into a new window that IS properly
// attached via -initWithWindowScene:. Nothing about RN's own setup changes
// -- this only re-parents the already-built root view controller.
//
// A cold launch via a URL (e.g. the dev-client's exp+wordquest:// deep link
// naming the Metro server to use) is delivered here, in
// connectionOptions.URLContexts / .userActivities -- NOT via
// -scene:openURLContexts:, which only fires once the app is already
// running. Forward both through the same app-level handlers used there, so
// a cold-started QR scan actually reaches RCTLinkingManager / the
// dev-launcher instead of being silently dropped.
- (void)scene:(UIScene *)scene
    willConnectToSession:(UISceneSession *)session
                 options:(UISceneConnectionOptions *)connectionOptions
{
  // self here is a SEPARATE instance from the UIApplicationDelegate
  // singleton that -application:didFinishLaunchingWithOptions: ran on --
  // UIKit always allocates a fresh object for scene-delegate duties, even
  // though UISceneDelegateClassName names this same class. self.window is
  // therefore a distinct, never-populated ivar and is ALWAYS nil here, on
  // every launch. Pull the real, already-built window/rootViewController
  // off the actual app-delegate singleton instead.
  id<UIApplicationDelegate> appDelegate = [UIApplication sharedApplication].delegate;
  UIWindow *builtWindow = appDelegate.window;
  if (![scene isKindOfClass:[UIWindowScene class]] || !builtWindow) {
    return;
  }
  UIWindowScene *windowScene = (UIWindowScene *)scene;
  UIViewController *rootViewController = builtWindow.rootViewController;
  UIWindow *sceneWindow = [[UIWindow alloc] initWithWindowScene:windowScene];
  sceneWindow.rootViewController = rootViewController;
  self.window = sceneWindow;
  // Keep the app-delegate singleton's own window in sync too: plain
  // UIApplicationDelegate methods (application:openURL:options:, remote
  // notification callbacks, etc.) run on THAT instance and read *its*
  // self.window, not this scene delegate's.
  appDelegate.window = sceneWindow;
  [self.window makeKeyAndVisible];

  for (UIOpenURLContext *context in connectionOptions.URLContexts) {
    NSMutableDictionary<UIApplicationOpenURLOptionsKey, id> *options = [NSMutableDictionary dictionary];
    if (context.options.sourceApplication) {
      options[UIApplicationOpenURLOptionsSourceApplicationKey] = context.options.sourceApplication;
    }
    if (context.options.annotation) {
      options[UIApplicationOpenURLOptionsAnnotationKey] = context.options.annotation;
    }
    options[UIApplicationOpenURLOptionsOpenInPlaceKey] = @(context.options.openInPlace);
    [self application:[UIApplication sharedApplication] openURL:context.URL options:options];
  }

  for (NSUserActivity *userActivity in connectionOptions.userActivities) {
    [self application:[UIApplication sharedApplication]
        continueUserActivity:userActivity
           restorationHandler:^(NSArray<id<UIUserActivityRestoring>> *_Nullable restorableObjects) {
           }];
  }
}

`;

    config.modResults.contents = config.modResults.contents.replace(anchor, snippet + anchor);
    return config;
  });
};
