/* eslint-disable @typescript-eslint/no-var-requires -- Expo config plugins run as plain CommonJS under Node, outside the app's TS/babel pipeline */
const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Several CocoaPods dependencies (the individual Expo modules — EXApplication,
 * EXConstants, EXNotifications, etc. — each ship as their own pod) declare an
 * older iOS deployment target in their own podspec. The Podfile's
 * `platform :ios, podfile_properties['ios.deploymentTarget']` line (driven by
 * expo-build-properties' ios.deploymentTarget setting in app.json) only sets
 * a Podfile-wide default — CocoaPods does not reliably raise a pod that
 * already declares its own (lower) deployment target up to match, so those
 * pods stayed on their old target even after we bumped the app itself to
 * 15.1, and Xcode flagged every one of them as a deployment-target mismatch.
 *
 * CocoaPods only allows ONE `post_install` hook per Podfile (a second,
 * separate `post_install do |installer| ... end` block fails Podfile
 * validation outright: "Specifying multiple `post_install` hooks is
 * unsupported"), so this can't just append a second hook — it has to splice
 * into Expo's existing one, right after the `react_native_post_install(...)`
 * call, and walk every pod target raising its IPHONEOS_DEPLOYMENT_TARGET to
 * match whenever it's lower (never lowering a pod that genuinely needs
 * something newer).
 *
 * Runs on every `expo prebuild` (clean or not), so this survives a full
 * native-project regen the same way the expo-build-properties deployment
 * target fix does — no manual re-patching needed after this.
 */
module.exports = function withPodDeploymentTarget(config) {
  return withDangerousMod(config, [
    'ios',
    (config) => {
      const podfilePath = path.join(config.modRequest.platformProjectRoot, 'Podfile');
      let contents = fs.readFileSync(podfilePath, 'utf-8');
      const marker = '# @generated by withPodDeploymentTarget (do not edit by hand)';
      if (contents.includes(marker)) {
        return config;
      }

      // Anchored on the end of Expo's own react_native_post_install(...) call
      // (inside the Podfile's single post_install hook), which every Expo
      // SDK 51 template Podfile has — fails loudly instead of silently doing
      // nothing if that call's shape ever changes.
      const anchorPattern =
        /(:ccache_enabled\s*=>\s*podfile_properties\['apple\.ccacheEnabled'\]\s*==\s*'true',\s*\n\s*\)\n)/;
      const match = contents.match(anchorPattern);
      if (!match) {
        throw new Error(
          "withPodDeploymentTarget: could not find the react_native_post_install(...) call in the Podfile to splice into — Expo's Podfile template may have changed.",
        );
      }

      const snippet = `
    ${marker}
    deployment_target = (podfile_properties['ios.deploymentTarget'] || '13.4').to_f
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        current = build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        if current.nil? || current.to_f < deployment_target
          build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target.to_s
        end
      end
    end
`;

      contents = contents.replace(anchorPattern, match[1] + snippet);
      fs.writeFileSync(podfilePath, contents);
      return config;
    },
  ]);
};
