/* eslint-disable @typescript-eslint/no-var-requires -- Expo config plugins run as plain CommonJS under Node, outside the app's TS/babel pipeline */
const { withAppDelegate } = require('@expo/config-plugins');

/**
 * RCTAppDelegate's own -application:didFinishLaunchingWithOptions: creates
 * self.window with -initWithFrame: before any UIScene exists -- it predates
 * React Native's scene support being mandatory. Xcode 27 / iOS 27 enforce
 * UIScene adoption as a hard launch requirement (see withPodDeploymentTarget
 * / the ios.infoPlist UIApplicationSceneManifest entry in app.json, which
 * point AppDelegate at itself as the scene delegate -- RCTAppDelegate
 * already formally conforms to UISceneDelegate). Declaring the scene
 * delegate alone is enough to stop the launch-time crash, but a window
 * created via -initWithFrame: never actually gets composited once scenes
 * are enforced, and UIWindow.windowScene is read-only so it can't just be
 * attached after the fact -- the result is a real, running app showing a
 * blank black screen.
 *
 * This adds -scene:willConnectToSession:options: to AppDelegate.mm, which
 * re-hosts the same rootViewController RN's own bootstrapping already built
 * into a new window that IS properly attached via -initWithWindowScene:.
 * Nothing about RN's own setup changes -- this only re-parents the
 * already-built root view controller once the scene becomes available.
 *
 * Runs on every prebuild (clean or not), matching withPodDeploymentTarget.
 */
module.exports = function withSceneDelegateWindow(config) {
  return withAppDelegate(config, (config) => {
    const marker = '// @generated by withSceneDelegateWindow (do not edit by hand)';
    if (config.modResults.contents.includes(marker)) {
      return config;
    }

    const anchor = '- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge';
    if (!config.modResults.contents.includes(anchor)) {
      throw new Error(
        "withSceneDelegateWindow: could not find the anchor method in AppDelegate.mm to splice into -- Expo's AppDelegate template may have changed.",
      );
    }

    const snippet = `${marker}
// RCTAppDelegate's own -application:didFinishLaunchingWithOptions: (called
// via super, above) creates self.window with -initWithFrame: before any
// UIScene exists -- it predates React Native's scene support being
// mandatory. Now that Xcode 27 / iOS 27 enforce UIScene adoption, a window
// created that way never actually gets composited on screen, and
// UIWindow.windowScene is read-only so it can't just be attached after the
// fact. Once the scene connects, re-host the same rootViewController (built
// by RN's own bootstrapping above) into a new window that IS properly
// attached via -initWithWindowScene:. Nothing about RN's own setup changes
// -- this only re-parents the already-built root view controller.
- (void)scene:(UIScene *)scene
    willConnectToSession:(UISceneSession *)session
                 options:(UISceneConnectionOptions *)connectionOptions
{
  if (![scene isKindOfClass:[UIWindowScene class]] || !self.window) {
    return;
  }
  UIWindowScene *windowScene = (UIWindowScene *)scene;
  UIViewController *rootViewController = self.window.rootViewController;
  UIWindow *sceneWindow = [[UIWindow alloc] initWithWindowScene:windowScene];
  sceneWindow.rootViewController = rootViewController;
  self.window = sceneWindow;
  [self.window makeKeyAndVisible];
}

`;

    config.modResults.contents = config.modResults.contents.replace(anchor, snippet + anchor);
    return config;
  });
};
