const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Several CocoaPods dependencies (the individual Expo modules — EXApplication,
 * EXConstants, EXNotifications, etc. — each ship as their own pod) declare an
 * older iOS deployment target in their own podspec. The Podfile's
 * `platform :ios, podfile_properties['ios.deploymentTarget']` line (driven by
 * expo-build-properties' ios.deploymentTarget setting in app.json) only sets
 * a Podfile-wide default — CocoaPods does not reliably raise a pod that
 * already declares its own (lower) deployment target up to match, so those
 * pods stayed on their old target even after we bumped the app itself to
 * 15.1, and Xcode flagged every one of them as a deployment-target mismatch.
 *
 * This appends a second `post_install` hook to the generated Podfile —
 * CocoaPods runs every post_install hook it's given, so it runs alongside
 * Expo's own `react_native_post_install` rather than replacing it — that
 * walks every pod target and raises its IPHONEOS_DEPLOYMENT_TARGET to match
 * ios.deploymentTarget whenever the pod's own value is lower, and leaves it
 * alone otherwise (never lowers a pod that genuinely needs something newer).
 *
 * Runs on every `expo prebuild` (clean or not), so this survives a full
 * native-project regen the same way the expo-build-properties deployment
 * target fix does — no manual re-patching needed after this.
 */
module.exports = function withPodDeploymentTarget(config) {
  return withDangerousMod(config, [
    'ios',
    (config) => {
      const podfilePath = path.join(config.modRequest.platformProjectRoot, 'Podfile');
      let contents = fs.readFileSync(podfilePath, 'utf-8');
      const marker = '# @generated by withPodDeploymentTarget (do not edit by hand)';
      if (contents.includes(marker)) {
        return config;
      }

      const snippet = `
${marker}
post_install do |installer|
  deployment_target = (podfile_properties['ios.deploymentTarget'] || '13.4').to_f
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |build_config|
      current = build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      if current.nil? || current.to_f < deployment_target
        build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target.to_s
      end
    end
  end
end
`;

      fs.writeFileSync(podfilePath, contents.trimEnd() + '\n' + snippet);
      return config;
    },
  ]);
};
