import {
  BadRequestException,
  ConflictException,
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import { ProgressionService } from '../../progression/progression.service';
import { isUniqueConstraintError } from '../../common/prisma-errors';
import { ArcadeChallengeService } from '../challenge.service';
import { ArcadeVersusService } from '../versus/versus.service';
import { ArcadePlayLimitService, type ArcadePlayNotice } from '../limits/play-limit.service';
import { RewardEngineService } from '../reward-engine.service';
import { nextStreak } from '../types';
import { normalizeAnswer } from '../answer-normalization';
import { ARCADE_COUNTS_TOWARD_DAILY_STREAK, SCRAMBLE_QUEST_CONFIG } from '../config/arcade.config';
import { hintRevealOrder, scrambleWord } from './scramble.util';
import { renderWord } from '../../vocabulary/english-variant';
import { resolveEnglishVariant } from '../../vocabulary/resolve-english-variant';
import {
  AliService,
  type AliEvent,
  type AliDisplayMessage,
  toAliDisplayMessage,
} from '../../ali/ali.service';
import { quickAliReaction } from '../../ali/ali-quick-reactions';
import { quickAliExpression, type AliExpressionCue } from '../../ali/ali-expression';

/** Client-safe view of the player's current ScrambleQuest word — the
 * scrambled letters, never the target word (spec §5/§8). */
export interface ScrambleQuestChallengeView {
  /** Present only on the response that started a new play: the player's
   * standing against the daily cap (and the 50/70/90/100 percent notice, if crossed). */
  playLimit?: ArcadePlayNotice;
  sessionId: string;
  wordIndex: number;
  wordsTotal: number;
  scrambledLetters: string;
  wordLength: number;
  /** Always shown under the puzzle, not gated behind a hint — Barth,
   * Sept 2026 design review: "the word is supposed to have the
   * dictionary meaning under it". */
  definition: string;
  /** Optional, player-initiated reveal (a "Synonyms" card the mobile
   * screen shows behind a toggle) — included here unconditionally since
   * showing it is purely a client-side choice with no server-tracked
   * state and, per Barth, must never affect XP the way the letter-reveal
   * Hint button does. */
  synonyms: string[];
  timeLimitSeconds: number;
  /** ISO timestamp — server-authoritative deadline for this word. Render
   * a countdown from it; never decide anything about timing client-side
   * (spec §10/§11). */
  deadlineAt: string;
  hintsRemaining: number;
  maxHints: number;
  /** Hints already spent on this word, so a resumed/re-fetched challenge
   * (app relaunch mid-word) shows the same revealed letters instead of
   * "forgetting" them. */
  revealedLetters: { position: number; letter: string }[];
  currentStreak: number;
  longestStreak: number;
}

export interface ScrambleQuestHintResult {
  position: number;
  letter: string;
  hintsRemaining: number;
}

/** A completed word's meaning, surfaced only after it's been answered —
 * never while it's still the active puzzle (spec convention shared with
 * DailyQuest's UnderstandingContent: don't give the answer away before
 * the player has actually guessed it). */
export interface ScrambleQuestWordMeaning {
  definition: string;
  partOfSpeech: string;
  synonyms: string[];
}

export interface ScrambleQuestAnswerResult {
  isCorrect: boolean;
  timedOut: boolean;
  correctAnswer: string;
  xpAwarded: number;
  currentStreak: number;
  longestStreak: number;
  sessionComplete: boolean;
  /** Set on the last word of a head-to-head play: that play now counts toward the daily cap. */
  playLimit?: ArcadePlayNotice;
  totalXpAwarded: number;
  correctCount: number;
  wordsTotal: number;
  nextChallenge: ScrambleQuestChallengeView | null;
  /** This word's definition/part-of-speech/synonyms — populated once
   * it's been answered (correct, wrong, or timed out). The client
   * shows it behind an opt-in "Meaning & synonyms" card, not
   * automatically. */
  meaning: ScrambleQuestWordMeaning;
  /**
   * Populated only on the session's last word (task #99 follow-up):
   * a STREAK_MILESTONE reaction resolved live, right alongside
   * recordDailyActivity firing, for the client to pop out of the
   * streak container and back (AliStreakPopout) — never the general
   * ALI popup. null on every other word, and null on the last word too
   * when no milestone was hit.
   */
  streakReaction: AliDisplayMessage | null;
  /**
   * Populated only on the session's last word: any LEVEL_UP/
   * JOURNEY_COMPLETION reaction generated by an EARLIER answer this
   * session, read back via AliService.listReactionsSince rather than
   * shown live (mid-session ALI reactions stay fire-and-forget here —
   * see recordDailyActivity's own doc comment on why the Anthropic call
   * never blocks an answer submission). The client shows these as a
   * "while you were playing..." recap on the session-complete screen.
   * Always [] on a non-final word.
   */
  deferredAliReactions: AliDisplayMessage[];
  /**
   * A short, zero-cost ALI reaction to this specific answer (task #100
   * follow-up — same per-answer treatment Daily Quest/Boss Battle
   * already have, brought to ScrambleQuest). Null only when timedOut.
   */
  aliQuickReaction: string | null;
  /** The visual pairing for aliQuickReaction — see ali-expression.ts's
   * quickAliExpression. Null only alongside aliQuickReaction (timedOut). */
  aliQuickExpression: AliExpressionCue | null;
}

type ArcadeGameSessionRow = Prisma.ArcadeGameSessionGetPayload<Record<string, never>>;

/**
 * ScrambleQuest (spec §5): timed word unscrambling. One
 * ArcadeGameSession per play-through, its full word sequence picked once
 * at start via ArcadeChallengeService (spec §8) and stored on
 * wordIds/wordsTotal. All correctness, timing, hint-count, and streak
 * decisions are made here from server-held state only — nothing here
 * ever trusts a client-submitted hint count, elapsed time, or
 * correctness flag (spec §11).
 */
@Injectable()
export class ScrambleQuestService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly challenges: ArcadeChallengeService,
    private readonly rewardEngine: RewardEngineService,
    private readonly progression: ProgressionService,
    private readonly ali: AliService,
    private readonly versus: ArcadeVersusService,
    private readonly playLimit: ArcadePlayLimitService,
  ) {}

  /**
   * Starts a new session, or resumes one already in progress (an app
   * relaunch mid-session) as long as the current word's server-side
   * timer hasn't already run out. A resumable-but-expired session is
   * abandoned first, never left ACTIVE forever with no way to progress.
   */
  async start(userId: string, versusMatchId?: string): Promise<ScrambleQuestChallengeView> {
    if (versusMatchId) return this.startVersus(userId, versusMatchId);
    const existing = await this.prisma.arcadeGameSession.findFirst({
      where: { userId, game: 'SCRAMBLE_QUEST', status: 'ACTIVE', versusMatchId: null },
    });
    const variant = await resolveEnglishVariant(this.prisma, userId);

    if (existing) {
      const deadlineMs =
        existing.currentWordStartedAt.getTime() + SCRAMBLE_QUEST_CONFIG.TIMER_SECONDS * 1000;
      if (Date.now() < deadlineMs) {
        return this.buildChallengeView(existing, variant);
      }
      await this.prisma.arcadeGameSession.update({
        where: { id: existing.id },
        data: { status: 'ABANDONED', endedAt: new Date() },
      });
    }

    await this.playLimit.assertCanPlay(userId, 'SCRAMBLE_QUEST');

    const picked = await this.challenges.pickChallenges(
      userId,
      SCRAMBLE_QUEST_CONFIG.WORDS_PER_SESSION,
      [],
      SCRAMBLE_QUEST_CONFIG.MIN_WORD_LENGTH,
      SCRAMBLE_QUEST_CONFIG.MAX_WORD_LENGTH,
    );
    if (picked.length === 0) {
      throw new BadRequestException('No words are available for ScrambleQuest right now.');
    }

    // Taken before the session exists, so a refused (raced) play never leaves a free session behind.
    const playLimit = await this.playLimit.consumePlay(userId, 'SCRAMBLE_QUEST');
    const session = await this.prisma.arcadeGameSession.create({
      data: {
        userId,
        game: 'SCRAMBLE_QUEST',
        wordsTotal: picked.length,
        wordIds: picked.map((c) => c.word.id),
      },
    });

    return { ...(await this.buildChallengeView(session, variant)), playLimit };
  }

  /**
   * Opens this player's half of a head-to-head match: the same session as a
   * solo play, but on the match's shared word list (picked by whichever
   * player starts first) and tied to the match. A relaunch resumes it.
   */
  private async startVersus(userId: string, versusMatchId: string) {
    const variant = await resolveEnglishVariant(this.prisma, userId);
    const resolved = await this.versus.resolveStart(userId, versusMatchId, 'SCRAMBLE_QUEST', async () =>
      (
        await this.challenges.pickChallenges(
          userId,
          SCRAMBLE_QUEST_CONFIG.WORDS_PER_SESSION,
          [],
          SCRAMBLE_QUEST_CONFIG.MIN_WORD_LENGTH,
          SCRAMBLE_QUEST_CONFIG.MAX_WORD_LENGTH,
        )
      ).map((c) => c.word.id),
    );
    if (resolved.existing) return this.buildChallengeView(resolved.existing, variant);

    // A head-to-head play is counted when it is finished (see submitAnswer),
    // so starting only checks that today's plays are not already used up.
    await this.playLimit.assertCanPlay(userId, 'SCRAMBLE_QUEST');

    try {
      const session = await this.prisma.arcadeGameSession.create({
        data: {
          userId,
          game: 'SCRAMBLE_QUEST',
          wordsTotal: resolved.wordIds.length,
          wordIds: resolved.wordIds,
          versusMatchId,
        },
      });
      return this.buildChallengeView(session, variant);
    } catch (err) {
      // A double-tap raced us: the other request already created it.
      if (!isUniqueConstraintError(err)) throw err;
      const existing = await this.prisma.arcadeGameSession.findUniqueOrThrow({
        where: { versusMatchId_userId: { versusMatchId, userId } },
      });
      return this.buildChallengeView(existing, variant);
    }
  }

  /**
   * Reveals the next letter (left to right) of the current word. Up to
   * SCRAMBLE_QUEST_CONFIG.MAX_HINTS_PER_WORD, capped further so a hint
   * can never reveal the word's very last letter (spec doesn't require
   * this, but a hint that fully solves the word isn't really a hint).
   */
  async requestHint(userId: string, sessionId: string): Promise<ScrambleQuestHintResult> {
    const session = await this.loadActiveSession(userId, sessionId);
    const word = await this.currentWord(session);
    const variant = await resolveEnglishVariant(this.prisma, userId);
    const rendered = renderWord(word, variant);
    const maxHintsForWord = this.maxHintsFor(rendered.text);

    if (session.currentWordHintsUsed >= maxHintsForWord) {
      throw new BadRequestException(`No hints remaining (max ${maxHintsForWord}).`);
    }

    // Compare-and-swap on the exact hint count just read — a race loser
    // (double-tap, or two requests in flight) can't both succeed and
    // silently grant an extra hint.
    const claimed = await this.prisma.arcadeGameSession.updateMany({
      where: { id: sessionId, currentWordHintsUsed: session.currentWordHintsUsed },
      data: { currentWordHintsUsed: { increment: 1 } },
    });
    if (claimed.count === 0) {
      throw new ConflictException('This hint was already requested');
    }

    // The Nth hint reveals a randomized (but deterministic-per-session)
    // position, not simply the Nth letter — see hintRevealOrder(). Uses
    // the RENDERED (variant-aware) spelling so the revealed letter
    // always matches what this player actually sees on screen (2026-09
    // fairness feature).
    const hintsUsedNow = session.currentWordHintsUsed + 1;
    const revealOrder = hintRevealOrder(
      rendered.text,
      `${session.id}:${session.currentIndex}:hints`,
    );
    const position = revealOrder[session.currentWordHintsUsed];
    return {
      position,
      letter: rendered.text[position],
      hintsRemaining: maxHintsForWord - hintsUsedNow,
    };
  }

  async submitAnswer(
    userId: string,
    sessionId: string,
    rawAnswer: string,
  ): Promise<ScrambleQuestAnswerResult> {
    const session = await this.loadActiveSession(userId, sessionId);
    const word = await this.currentWord(session);
    const variant = await resolveEnglishVariant(this.prisma, userId);
    const rendered = renderWord(word, variant);

    // Server-authoritative timing (spec §10/§11) — always computed from
    // the server-recorded currentWordStartedAt, never a client-reported
    // elapsed time.
    const responseTimeMs = Date.now() - session.currentWordStartedAt.getTime();
    const timeLimitMs = SCRAMBLE_QUEST_CONFIG.TIMER_SECONDS * 1000;
    const timedOut = responseTimeMs > timeLimitMs;
    // Compared against the RENDERED (variant-aware) form — a US-preference
    // player typing "color" for a word whose UK headword is "colour"
    // must be marked correct (2026-09 fairness feature).
    const isCorrect = !timedOut && normalizeAnswer(rawAnswer) === rendered.normalizedText;
    const aliQuickReaction = timedOut ? null : quickAliReaction(isCorrect);
    const aliQuickExpression = timedOut ? null : quickAliExpression(isCorrect);

    const streakBefore = session.currentStreak;
    const streakAfter = nextStreak(streakBefore, { isCorrect, timedOut });
    const newLongestStreak = Math.max(session.longestStreak, streakAfter);

    let reward = { baseXp: 0, speedModifier: 1, hintModifier: 1, streakModifier: 1, finalXp: 0 };
    if (isCorrect) {
      reward = this.rewardEngine.calculate({
        difficulty: word.baseDifficulty,
        responseTimeMs,
        timeLimitMs,
        hintsUsed: session.currentWordHintsUsed,
        streakBefore,
      });
    }

    const wordIndex = session.currentIndex;
    const isLastWord = wordIndex + 1 >= session.wordsTotal;

    // Collects a STREAK_MILESTONE descriptor (if this last word's
    // recordDailyActivity crosses one) instead of firing it via
    // reactFireAndForget — see ScrambleQuestAnswerResult's
    // streakReaction doc comment for why this word needs it resolved
    // live rather than only landing in ALI's message feed.
    const aliEvents: AliEvent[] = [];

    const { correctCount } = await this.prisma.$transaction(
      async (tx: Prisma.TransactionClient) => {
        try {
          await tx.arcadeAnswer.create({
            data: {
              sessionId,
              wordIndex,
              wordId: word.id,
              submittedAnswer: rawAnswer,
              isCorrect,
              hintsUsed: session.currentWordHintsUsed,
              timedOut,
              baseXp: reward.baseXp,
              speedModifier: reward.speedModifier,
              hintModifier: reward.hintModifier,
              streakModifier: reward.streakModifier,
              finalXpAwarded: reward.finalXp,
              streakBefore,
              streakAfter,
              responseTimeMs,
            },
          });
        } catch (err) {
          // @@unique([sessionId, wordIndex]) — the idempotency/duplicate-
          // submission guard (spec §9/§11): a retried or racing second
          // submission for the same word never reaches the award below.
          if (isUniqueConstraintError(err)) {
            throw new ConflictException('This word was already answered');
          }
          throw err;
        }

        // Claim the session's advance — before the XP award — so a race
        // loser aborts cleanly instead of double-awarding. The unique
        // constraint above already catches this in practice; this is
        // defense in depth, mirroring QuestsService.claimStageTransition.
        const claimed = await tx.arcadeGameSession.updateMany({
          where: { id: sessionId, currentIndex: wordIndex },
          data: {
            currentIndex: { increment: 1 },
            currentStreak: streakAfter,
            longestStreak: newLongestStreak,
            totalXpAwarded: { increment: reward.finalXp },
            currentWordStartedAt: new Date(),
            currentWordHintsUsed: 0,
            ...(isLastWord ? { status: 'COMPLETED' as const, endedAt: new Date() } : {}),
          },
        });
        if (claimed.count === 0) {
          throw new ConflictException('This word was already answered');
        }

        if (isCorrect) {
          // ProgressionService is the ONLY writer of account XP (spec §3)
          // — reference ties this award back to the exact answer for
          // auditing, same convention as QUEST_ANSWER/QUEST_COMPLETION.
          await this.progression.awardXp(
            userId,
            reward.finalXp,
            'ARCADE_SCRAMBLE_QUEST_ANSWER',
            'arcade',
            `${sessionId}:${wordIndex}`,
            tx,
          );
        }

        const correctSoFar = await tx.arcadeAnswer.count({ where: { sessionId, isCorrect: true } });

        // Daily-activity streak counts once, on full session completion —
        // matching Daily Quest's own semantics (recordDailyActivity fires
        // on QUEST_COMPLETION, not on every answer) so a trivial partial
        // session can't farm the streak. 2026-09 decision: Arcade play
        // DOES count (ARCADE_COUNTS_TOWARD_DAILY_STREAK).
        if (isLastWord && ARCADE_COUNTS_TOWARD_DAILY_STREAK) {
          await this.progression.recordDailyActivity(userId, tx, aliEvents);
        }

        return { correctCount: correctSoFar };
      },
    );

    let nextChallenge: ScrambleQuestChallengeView | null = null;
    if (!isLastWord) {
      const refreshed = await this.prisma.arcadeGameSession.findUniqueOrThrow({
        where: { id: sessionId },
      });
      nextChallenge = await this.buildChallengeView(refreshed, variant);
    }

    // Best-effort, after the transaction commits — same policy as
    // Daily Quest's completeWord (never lets an ALI failure roll back
    // progress that already committed). Only ever does anything on the
    // session's last word: aliEvents is empty on every earlier one.
    let streakReaction: AliDisplayMessage | null = null;
    let deferredAliReactions: AliDisplayMessage[] = [];
    if (isLastWord) {
      await Promise.all(
        aliEvents.map(async (event) => {
          try {
            streakReaction = toAliDisplayMessage(await this.ali.react(userId, event));
          } catch {
            // Dropped — see the comment above.
          }
        }),
      );
      try {
        deferredAliReactions = await this.ali.listReactionsSince(
          userId,
          session.startedAt,
          AliService.DEFERRED_REACTION_EVENT_TYPES,
        );
      } catch {
        // The results screen just won't show a recap this time.
      }
    }

    // A head-to-head play counts only once the player has played it to the
    // end: dropping out midway never uses up one of the day's plays. The
    // match is already committed, so this is recorded, never refused.
    let playLimit: ArcadePlayNotice | undefined;
    if (isLastWord && session.versusMatchId) {
      playLimit = await this.playLimit
        .consumePlay(userId, 'SCRAMBLE_QUEST', { force: true })
        .catch(() => undefined);
    }

    return {
      isCorrect,
      timedOut,
      correctAnswer: rendered.text,
      xpAwarded: reward.finalXp,
      currentStreak: streakAfter,
      longestStreak: newLongestStreak,
      sessionComplete: isLastWord,
      playLimit,
      totalXpAwarded: session.totalXpAwarded + reward.finalXp,
      correctCount,
      wordsTotal: session.wordsTotal,
      nextChallenge,
      streakReaction,
      deferredAliReactions,
      aliQuickReaction,
      aliQuickExpression,
      meaning: {
        definition: word.definition,
        partOfSpeech: word.partOfSpeech,
        synonyms: word.synonyms,
      },
    };
  }

  private async loadActiveSession(
    userId: string,
    sessionId: string,
  ): Promise<ArcadeGameSessionRow> {
    const session = await this.prisma.arcadeGameSession.findUnique({ where: { id: sessionId } });
    if (!session) throw new NotFoundException('ScrambleQuest session not found');
    if (session.userId !== userId) throw new ForbiddenException('Not your ScrambleQuest session');
    if (session.game !== 'SCRAMBLE_QUEST') {
      throw new BadRequestException('This session is not a ScrambleQuest session');
    }
    if (session.status !== 'ACTIVE') {
      throw new BadRequestException('This ScrambleQuest session has already ended');
    }
    return session;
  }

  private currentWord(session: Pick<ArcadeGameSessionRow, 'wordIds' | 'currentIndex'>) {
    const wordId = session.wordIds[session.currentIndex];
    return this.prisma.word.findUniqueOrThrow({ where: { id: wordId } });
  }

  /** A hint can never reveal the word's final letter — leaves at least
   * one letter for the player to actually solve. */
  private maxHintsFor(word: string): number {
    return Math.min(SCRAMBLE_QUEST_CONFIG.MAX_HINTS_PER_WORD, Math.max(0, word.length - 1));
  }

  private async buildChallengeView(
    session: ArcadeGameSessionRow,
    variant: 'US' | 'UK' | null,
  ): Promise<ScrambleQuestChallengeView> {
    const word = await this.currentWord(session);
    const rendered = renderWord(word, variant);
    const maxHintsForWord = this.maxHintsFor(rendered.text);
    const revealOrder = hintRevealOrder(
      rendered.text,
      `${session.id}:${session.currentIndex}:hints`,
    );
    const revealedLetters = revealOrder.slice(0, session.currentWordHintsUsed).map((position) => ({
      position,
      letter: rendered.text[position],
    }));

    return {
      sessionId: session.id,
      wordIndex: session.currentIndex,
      wordsTotal: session.wordsTotal,
      scrambledLetters: scrambleWord(rendered.text, `${session.id}:${session.currentIndex}`),
      wordLength: rendered.text.length,
      definition: word.definition,
      synonyms: word.synonyms,
      timeLimitSeconds: SCRAMBLE_QUEST_CONFIG.TIMER_SECONDS,
      deadlineAt: new Date(
        session.currentWordStartedAt.getTime() + SCRAMBLE_QUEST_CONFIG.TIMER_SECONDS * 1000,
      ).toISOString(),
      hintsRemaining: maxHintsForWord - session.currentWordHintsUsed,
      maxHints: maxHintsForWord,
      revealedLetters,
      currentStreak: session.currentStreak,
      longestStreak: session.longestStreak,
    };
  }
}
