import {
  BadRequestException,
  ConflictException,
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import { ProgressionService } from '../../progression/progression.service';
import { isUniqueConstraintError } from '../../common/prisma-errors';
import { ArcadeChallengeService } from '../challenge.service';
import { ArcadeVersusService } from '../versus/versus.service';
import { ArcadeGroupService } from '../group/group.service';
import { ArcadePlayLimitService, type ArcadePlayNotice } from '../limits/play-limit.service';
import { RewardEngineService } from '../reward-engine.service';
import { nextStreak } from '../types';
import { normalizeAnswer } from '../answer-normalization';
import { ARCADE_COUNTS_TOWARD_DAILY_STREAK, COMPLETE_IT_CONFIG } from '../config/arcade.config';
import { blankSentence, isCompleteItSentenceUsable } from './complete-it.util';
import { hintRevealOrder } from '../scramble-quest/scramble.util';
import { renderWord } from '../../vocabulary/english-variant';
import { resolveEnglishVariant } from '../../vocabulary/resolve-english-variant';
import {
  AliService,
  type AliEvent,
  type AliDisplayMessage,
  toAliDisplayMessage,
} from '../../ali/ali.service';
import { quickAliReaction } from '../../ali/ali-quick-reactions';
import { quickAliExpression, type AliExpressionCue } from '../../ali/ali-expression';

/** Client-safe view of the player's current Complete It word — the
 * word's own example sentence with the target word blanked out, never
 * the target word itself (spec §5/§8). */
export interface CompleteItChallengeView {
  /** Present only on the response that started a new play: the player's
   * standing against the daily cap (and the 50/70/90/100 percent notice, if crossed). */
  playLimit?: ArcadePlayNotice;
  sessionId: string;
  wordIndex: number;
  wordsTotal: number;
  sentenceWithBlank: string;
  definition: string;
  partOfSpeech: string;
  wordLength: number;
  timeLimitSeconds: number;
  /** ISO timestamp — server-authoritative deadline for this word. Render
   * a countdown from it; never decide anything about timing client-side
   * (spec §10/§11). */
  deadlineAt: string;
  hintsRemaining: number;
  maxHints: number;
  /** Hints already spent on this word, so a resumed/re-fetched challenge
   * (app relaunch mid-word) shows the same revealed letters instead of
   * "forgetting" them -- same convention as ScrambleQuestChallengeView. */
  revealedLetters: { position: number; letter: string }[];
  currentStreak: number;
  longestStreak: number;
}

export interface CompleteItHintResult {
  position: number;
  letter: string;
  hintsRemaining: number;
}

export interface CompleteItAnswerResult {
  isCorrect: boolean;
  timedOut: boolean;
  correctAnswer: string;
  xpAwarded: number;
  currentStreak: number;
  longestStreak: number;
  sessionComplete: boolean;
  /** Set on the last word of a head-to-head play: that play now counts toward the daily cap. */
  playLimit?: ArcadePlayNotice;
  totalXpAwarded: number;
  correctCount: number;
  wordsTotal: number;
  nextChallenge: CompleteItChallengeView | null;
  /**
   * Populated only on the session's last word (task #99 follow-up):
   * a STREAK_MILESTONE reaction resolved live, right alongside
   * recordDailyActivity firing, for the client to pop out of the
   * streak container and back (AliStreakPopout) — never the general
   * ALI popup. null on every other word, and null on the last word too
   * when no milestone was hit.
   */
  streakReaction: AliDisplayMessage | null;
  /**
   * Populated only on the session's last word: any LEVEL_UP/
   * JOURNEY_COMPLETION reaction generated by an EARLIER answer this
   * session, read back via AliService.listReactionsSince rather than
   * shown live — mid-session ALI reactions stay fire-and-forget here.
   * The client shows these as a "while you were playing..." recap on
   * the session-complete screen. Always [] on a non-final word.
   */
  deferredAliReactions: AliDisplayMessage[];
  /**
   * A short, zero-cost ALI reaction to this specific answer (task #100
   * follow-up — same per-answer treatment Daily Quest/Boss Battle
   * already have, brought to Complete It). Null only when timedOut.
   */
  aliQuickReaction: string | null;
  /** The visual pairing for aliQuickReaction — see ali-expression.ts's
   * quickAliExpression. Null only alongside aliQuickReaction (timedOut). */
  aliQuickExpression: AliExpressionCue | null;
}

type ArcadeGameSessionRow = Prisma.ArcadeGameSessionGetPayload<Record<string, never>>;

/**
 * Complete It (spec §5 sibling of ScrambleQuest): the player sees the
 * word's own example sentence with the target word blanked out, plus
 * its definition and part of speech, and types the missing word.
 * Shares ArcadeGameSession/ArcadeAnswer with ScrambleQuest (schema
 * comment: "ScrambleQuest or Complete It") — same session lifecycle,
 * same [sessionId, wordIndex] idempotency guard, same reward formula.
 * Hints work the same way ScrambleQuest's do (an on-demand, server-
 * tracked requestHint call that reveals one more letter of the target
 * word and increments currentWordHintsUsed, which then feeds the same
 * shared hintModifierFor XP penalty) -- the only difference is how many
 * hints a word gets: COMPLETE_IT_CONFIG.HINT_PERCENTAGE_OF_WORD_LENGTH
 * (60%) of the word's own letter count, rounded, instead of
 * ScrambleQuest's flat MAX_HINTS_PER_WORD (2026-09 decision, Barth).
 * See maxHintsFor.
 *
 * TIMER_SECONDS wasn't in the spec's own Complete It config (only
 * HINTS_ENABLED/WORDS_PER_SESSION were) even though the shared
 * speedModifierFor doc comment says it applies "identically" to all
 * three games — added here as the same kind of 2026-09 product
 * decision ScrambleQuest's own timer already was, slightly longer
 * since Complete It gives no letters at all up front, only sentence
 * context (see arcade.config.ts).
 */
@Injectable()
export class CompleteItService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly challenges: ArcadeChallengeService,
    private readonly rewardEngine: RewardEngineService,
    private readonly progression: ProgressionService,
    private readonly ali: AliService,
    private readonly versus: ArcadeVersusService,
    private readonly playLimit: ArcadePlayLimitService,
    private readonly group: ArcadeGroupService,
  ) {}

  /**
   * Starts a new session, or resumes one already in progress as long as
   * the current word's server-side timer hasn't already run out (same
   * pattern as ScrambleQuestService.start). The word pool is filtered
   * to sentences that both contain their own word AND read like a real
   * sentence — see isCompleteItSentenceUsable's doc comment — so
   * buildChallengeView never has to handle the "couldn't blank it"
   * case mid-session, and players never land on an unwinnable fragment.
   */
  async start(
    userId: string,
    versusMatchId?: string,
    groupId?: string,
  ): Promise<CompleteItChallengeView> {
    if (versusMatchId) return this.startVersus(userId, versusMatchId);
    if (groupId) return this.startGroup(userId, groupId);
    const existing = await this.prisma.arcadeGameSession.findFirst({
      where: { userId, game: 'COMPLETE_IT', status: 'ACTIVE', versusMatchId: null, groupId: null },
    });

    const variant = await resolveEnglishVariant(this.prisma, userId);

    if (existing) {
      const deadlineMs =
        existing.currentWordStartedAt.getTime() + COMPLETE_IT_CONFIG.TIMER_SECONDS * 1000;
      if (Date.now() < deadlineMs) {
        return this.buildChallengeView(existing, variant);
      }
      await this.prisma.arcadeGameSession.update({
        where: { id: existing.id },
        data: { status: 'ABANDONED', endedAt: new Date() },
      });
    }

    // The quality filter (isCompleteItSentenceUsable) is passed straight
    // into pickChallenges rather than applied after the fact -- it
    // rejects a meaningful fraction of the corpus (see complete-it.util
    // .ts's doc comment), so pickChallenges over-fetches and backfills
    // internally until it actually has WORDS_PER_SESSION usable words
    // (or the eligible pool runs out). Filtering after a single fixed-
    // size pick, the old approach, is what let sessions quietly ship
    // far fewer words than WORDS_PER_SESSION whenever the pick happened
    // to land on a lot of weak sentences.
    await this.playLimit.assertCanPlay(userId, 'COMPLETE_IT');

    const blankable = await this.challenges.pickChallenges(
      userId,
      COMPLETE_IT_CONFIG.WORDS_PER_SESSION,
      [],
      COMPLETE_IT_CONFIG.MIN_WORD_LENGTH,
      COMPLETE_IT_CONFIG.MAX_WORD_LENGTH,
      (c) => isCompleteItSentenceUsable(c.word.exampleSentence, c.word.word),
    );
    if (blankable.length === 0) {
      throw new BadRequestException('No words are available for Complete It right now.');
    }

    // A solo play counts only once the player finishes it (see submitAnswer):
    // starting just checked (above) that today's plays are not used up, and an
    // abandoned run never costs one.
    const session = await this.prisma.arcadeGameSession.create({
      data: {
        userId,
        game: 'COMPLETE_IT',
        wordsTotal: blankable.length,
        wordIds: blankable.map((c) => c.word.id),
      },
    });

    return this.buildChallengeView(session, variant);
  }

  /**
   * Opens this player's half of a head-to-head match: the same session as a
   * solo play, but on the match's shared word list (picked by whichever
   * player starts first) and tied to the match. A relaunch resumes it.
   */
  private async startVersus(userId: string, versusMatchId: string) {
    const variant = await resolveEnglishVariant(this.prisma, userId);
    const resolved = await this.versus.resolveStart(userId, versusMatchId, 'COMPLETE_IT', async () =>
      (
        await this.challenges.pickChallenges(
          userId,
          COMPLETE_IT_CONFIG.WORDS_PER_SESSION,
          [],
          COMPLETE_IT_CONFIG.MIN_WORD_LENGTH,
          COMPLETE_IT_CONFIG.MAX_WORD_LENGTH,
          (c) => isCompleteItSentenceUsable(c.word.exampleSentence, c.word.word),
        )
      ).map((c) => c.word.id),
    );
    if (resolved.existing) return this.buildChallengeView(resolved.existing, variant);

    // A head-to-head play is counted when it is finished (see submitAnswer),
    // so starting only checks that today's plays are not already used up.
    await this.playLimit.assertCanPlay(userId, 'COMPLETE_IT');

    try {
      const session = await this.prisma.arcadeGameSession.create({
        data: {
          userId,
          game: 'COMPLETE_IT',
          wordsTotal: resolved.wordIds.length,
          wordIds: resolved.wordIds,
          versusMatchId,
        },
      });
      return this.buildChallengeView(session, variant);
    } catch (err) {
      // A double-tap raced us: the other request already created it.
      if (!isUniqueConstraintError(err)) throw err;
      const existing = await this.prisma.arcadeGameSession.findUniqueOrThrow({
        where: { versusMatchId_userId: { versusMatchId, userId } },
      });
      return this.buildChallengeView(existing, variant);
    }
  }

  /**
   * Opens this member's play in a Group Play round: the same session as a
   * solo play, but on the group's shared word list (picked by whichever
   * member starts first) and tied to the group. A relaunch resumes it.
   * Group plays are not counted against the daily limit.
   */
  private async startGroup(userId: string, groupId: string) {
    const variant = await resolveEnglishVariant(this.prisma, userId);
    const resolved = await this.group.resolveStart(userId, groupId, 'COMPLETE_IT', async () =>
      (
        await this.challenges.pickChallenges(
          userId,
          COMPLETE_IT_CONFIG.WORDS_PER_SESSION,
          [],
          COMPLETE_IT_CONFIG.MIN_WORD_LENGTH,
          COMPLETE_IT_CONFIG.MAX_WORD_LENGTH,
          (c) => isCompleteItSentenceUsable(c.word.exampleSentence, c.word.word),
        )
      ).map((c) => c.word.id),
    );
    if (resolved.existing) return this.buildChallengeView(resolved.existing, variant);

    try {
      const session = await this.prisma.arcadeGameSession.create({
        data: {
          userId,
          game: 'COMPLETE_IT',
          wordsTotal: resolved.wordIds.length,
          wordIds: resolved.wordIds,
          groupId,
        },
      });
      return this.buildChallengeView(session, variant);
    } catch (err) {
      // A double-tap raced us: the other request already created it.
      if (!isUniqueConstraintError(err)) throw err;
      const existing = await this.prisma.arcadeGameSession.findUniqueOrThrow({
        where: { groupId_userId: { groupId, userId } },
      });
      return this.buildChallengeView(existing, variant);
    }
  }

  /**
   * Reveals the next hint letter of the current word (randomized but
   * deterministic-per-session order, same hintRevealOrder helper
   * ScrambleQuest uses) — up to maxHintsFor(word), capped so a hint can
   * never reveal the word's very last letter. Mirrors
   * ScrambleQuestService.requestHint exactly except for the hint-count
   * formula itself (see maxHintsFor).
   */
  async requestHint(userId: string, sessionId: string): Promise<CompleteItHintResult> {
    const session = await this.loadActiveSession(userId, sessionId);
    const word = await this.currentWord(session);
    const variant = await resolveEnglishVariant(this.prisma, userId);
    const rendered = renderWord(word, variant);
    const maxHintsForWord = this.maxHintsFor(rendered.text);

    if (session.currentWordHintsUsed >= maxHintsForWord) {
      throw new BadRequestException(`No hints remaining (max ${maxHintsForWord}).`);
    }

    // Compare-and-swap on the exact hint count just read — a race loser
    // (double-tap, or two requests in flight) can't both succeed and
    // silently grant an extra hint. Same pattern as
    // ScrambleQuestService.requestHint.
    const claimed = await this.prisma.arcadeGameSession.updateMany({
      where: { id: sessionId, currentWordHintsUsed: session.currentWordHintsUsed },
      data: { currentWordHintsUsed: { increment: 1 } },
    });
    if (claimed.count === 0) {
      throw new ConflictException('This hint was already requested');
    }

    const hintsUsedNow = session.currentWordHintsUsed + 1;
    const revealOrder = hintRevealOrder(
      rendered.text,
      `${session.id}:${session.currentIndex}:hints`,
    );
    const position = revealOrder[session.currentWordHintsUsed];
    return {
      position,
      letter: rendered.text[position],
      hintsRemaining: maxHintsForWord - hintsUsedNow,
    };
  }

  async submitAnswer(
    userId: string,
    sessionId: string,
    rawAnswer: string,
  ): Promise<CompleteItAnswerResult> {
    const session = await this.loadActiveSession(userId, sessionId);
    const word = await this.currentWord(session);
    const variant = await resolveEnglishVariant(this.prisma, userId);
    const rendered = renderWord(word, variant);

    // Server-authoritative timing (spec §10/§11) — always computed from
    // the server-recorded currentWordStartedAt, never a client-reported
    // elapsed time.
    const responseTimeMs = Date.now() - session.currentWordStartedAt.getTime();
    const timeLimitMs = COMPLETE_IT_CONFIG.TIMER_SECONDS * 1000;
    const timedOut = responseTimeMs > timeLimitMs;
    // Compared against the RENDERED (variant-aware) normalized form, not
    // word.normalizedWord directly -- a US-preference player who typed
    // "color" must be marked correct for a word whose UK-authored
    // answer is "colour" (2026-09 fairness feature).
    const isCorrect = !timedOut && normalizeAnswer(rawAnswer) === rendered.normalizedText;
    const aliQuickReaction = timedOut ? null : quickAliReaction(isCorrect);
    const aliQuickExpression = timedOut ? null : quickAliExpression(isCorrect);

    const streakBefore = session.currentStreak;
    const streakAfter = nextStreak(streakBefore, { isCorrect, timedOut });
    const newLongestStreak = Math.max(session.longestStreak, streakAfter);

    let reward = { baseXp: 0, speedModifier: 1, hintModifier: 1, streakModifier: 1, finalXp: 0 };
    if (isCorrect) {
      reward = this.rewardEngine.calculate({
        difficulty: word.baseDifficulty,
        responseTimeMs,
        timeLimitMs,
        hintsUsed: session.currentWordHintsUsed,
        streakBefore,
      });
    }

    const wordIndex = session.currentIndex;
    const isLastWord = wordIndex + 1 >= session.wordsTotal;

    // Collects a STREAK_MILESTONE descriptor (if this last word's
    // recordDailyActivity crosses one) instead of firing it via
    // reactFireAndForget — see CompleteItAnswerResult's streakReaction
    // doc comment for why this word needs it resolved live rather than
    // only landing in ALI's message feed.
    const aliEvents: AliEvent[] = [];

    const { correctCount } = await this.prisma.$transaction(
      async (tx: Prisma.TransactionClient) => {
        try {
          await tx.arcadeAnswer.create({
            data: {
              sessionId,
              wordIndex,
              wordId: word.id,
              submittedAnswer: rawAnswer,
              isCorrect,
              hintsUsed: session.currentWordHintsUsed,
              timedOut,
              baseXp: reward.baseXp,
              speedModifier: reward.speedModifier,
              hintModifier: reward.hintModifier,
              streakModifier: reward.streakModifier,
              finalXpAwarded: reward.finalXp,
              streakBefore,
              streakAfter,
              responseTimeMs,
            },
          });
        } catch (err) {
          // @@unique([sessionId, wordIndex]) — the idempotency/duplicate-
          // submission guard (spec §9/§11): a retried or racing second
          // submission for the same word never reaches the award below.
          if (isUniqueConstraintError(err)) {
            throw new ConflictException('This word was already answered');
          }
          throw err;
        }

        // Claim the session's advance — before the XP award — so a race
        // loser aborts cleanly instead of double-awarding (defense in
        // depth alongside the unique constraint above, mirroring
        // QuestsService.claimStageTransition / ScrambleQuestService).
        const claimed = await tx.arcadeGameSession.updateMany({
          where: { id: sessionId, currentIndex: wordIndex },
          data: {
            currentIndex: { increment: 1 },
            currentStreak: streakAfter,
            longestStreak: newLongestStreak,
            totalXpAwarded: { increment: reward.finalXp },
            currentWordStartedAt: new Date(),
            currentWordHintsUsed: 0,
            ...(isLastWord ? { status: 'COMPLETED' as const, endedAt: new Date() } : {}),
          },
        });
        if (claimed.count === 0) {
          throw new ConflictException('This word was already answered');
        }

        if (isCorrect) {
          // ProgressionService is the ONLY writer of account XP (spec §3).
          await this.progression.awardXp(
            userId,
            reward.finalXp,
            'ARCADE_COMPLETE_IT_ANSWER',
            'arcade',
            `${sessionId}:${wordIndex}`,
            tx,
          );
        }

        const correctSoFar = await tx.arcadeAnswer.count({ where: { sessionId, isCorrect: true } });

        // Daily-activity streak counts once, on full session completion —
        // same semantics as ScrambleQuestService/Daily Quest.
        if (isLastWord && ARCADE_COUNTS_TOWARD_DAILY_STREAK) {
          await this.progression.recordDailyActivity(userId, tx, aliEvents);
        }

        return { correctCount: correctSoFar };
      },
    );

    let nextChallenge: CompleteItChallengeView | null = null;
    if (!isLastWord) {
      const refreshed = await this.prisma.arcadeGameSession.findUniqueOrThrow({
        where: { id: sessionId },
      });
      nextChallenge = await this.buildChallengeView(refreshed, variant);
    }

    // Best-effort, after the transaction commits — same policy as
    // Daily Quest's completeWord. Only ever does anything on the
    // session's last word: aliEvents is empty on every earlier one.
    let streakReaction: AliDisplayMessage | null = null;
    let deferredAliReactions: AliDisplayMessage[] = [];
    if (isLastWord) {
      await Promise.all(
        aliEvents.map(async (event) => {
          try {
            streakReaction = toAliDisplayMessage(await this.ali.react(userId, event));
          } catch {
            // Dropped — see the comment above.
          }
        }),
      );
      try {
        deferredAliReactions = await this.ali.listReactionsSince(
          userId,
          session.startedAt,
          AliService.DEFERRED_REACTION_EVENT_TYPES,
        );
      } catch {
        // The results screen just won't show a recap this time.
      }
    }

    // A solo or head-to-head play counts only once the player has played it
    // to the end: dropping out midway never uses up one of the day's plays.
    // The run is already committed, so this is recorded, never refused.
    // (Group Play rounds are not counted against the daily limit.)
    let playLimit: ArcadePlayNotice | undefined;
    if (isLastWord && !session.groupId) {
      playLimit = await this.playLimit
        .consumePlay(userId, 'COMPLETE_IT', { force: true })
        .catch(() => undefined);
    }

    return {
      isCorrect,
      timedOut,
      correctAnswer: rendered.text,
      xpAwarded: reward.finalXp,
      currentStreak: streakAfter,
      longestStreak: newLongestStreak,
      sessionComplete: isLastWord,
      playLimit,
      totalXpAwarded: session.totalXpAwarded + reward.finalXp,
      correctCount,
      wordsTotal: session.wordsTotal,
      nextChallenge,
      streakReaction,
      deferredAliReactions,
      aliQuickReaction,
      aliQuickExpression,
    };
  }

  private async loadActiveSession(
    userId: string,
    sessionId: string,
  ): Promise<ArcadeGameSessionRow> {
    const session = await this.prisma.arcadeGameSession.findUnique({ where: { id: sessionId } });
    if (!session) throw new NotFoundException('Complete It session not found');
    if (session.userId !== userId) throw new ForbiddenException('Not your Complete It session');
    if (session.game !== 'COMPLETE_IT') {
      throw new BadRequestException('This session is not a Complete It session');
    }
    if (session.status !== 'ACTIVE') {
      throw new BadRequestException('This Complete It session has already ended');
    }
    return session;
  }

  private currentWord(session: Pick<ArcadeGameSessionRow, 'wordIds' | 'currentIndex'>) {
    const wordId = session.wordIds[session.currentIndex];
    return this.prisma.word.findUniqueOrThrow({ where: { id: wordId } });
  }

  /** A hint can never reveal the word's final letter -- leaves at least
   * one letter for the player to actually solve (same convention as
   * ScrambleQuestService.maxHintsFor). Sized to
   * HINT_PERCENTAGE_OF_WORD_LENGTH (60%) of the word's own letter
   * count, rounded to the nearest integer, rather than ScrambleQuest's
   * flat MAX_HINTS_PER_WORD -- e.g. 5 letters -> 3 hints, 10 letters ->
   * 6 hints. */
  private maxHintsFor(word: string): number {
    const percentageHints = Math.round(
      word.length * COMPLETE_IT_CONFIG.HINT_PERCENTAGE_OF_WORD_LENGTH,
    );
    return Math.min(percentageHints, Math.max(0, word.length - 1));
  }

  private async buildChallengeView(
    session: ArcadeGameSessionRow,
    variant: 'US' | 'UK' | null,
  ): Promise<CompleteItChallengeView> {
    const word = await this.currentWord(session);
    const rendered = renderWord(word, variant);
    // Guaranteed found:true — start() only ever puts blankable words
    // into wordIds (checked against the UK original; toUsSentence never
    // changes word count, see isCompleteItSentenceUsable's own note in
    // start(), so this holds for the rendered variant too). If this
    // were ever false it'd mean a data change happened after the
    // session started, which nothing in this app does; falling back to
    // the unblanked sentence would leak the answer, so this
    // deliberately does NOT have a silent fallback.
    const { sentenceWithBlank } = blankSentence(rendered.sentence, rendered.text);
    const maxHintsForWord = this.maxHintsFor(rendered.text);
    const revealOrder = hintRevealOrder(
      rendered.text,
      `${session.id}:${session.currentIndex}:hints`,
    );
    const revealedLetters = revealOrder.slice(0, session.currentWordHintsUsed).map((position) => ({
      position,
      letter: rendered.text[position],
    }));

    return {
      sessionId: session.id,
      wordIndex: session.currentIndex,
      wordsTotal: session.wordsTotal,
      sentenceWithBlank,
      definition: word.definition,
      partOfSpeech: word.partOfSpeech,
      // The rendered variant's own length, not word.word.length -- the
      // blank has to match what's actually on screen (e.g. "colour"
      // blanks to 6 underscores but its US form "color" blanks to 5).
      wordLength: rendered.text.length,
      timeLimitSeconds: COMPLETE_IT_CONFIG.TIMER_SECONDS,
      deadlineAt: new Date(
        session.currentWordStartedAt.getTime() + COMPLETE_IT_CONFIG.TIMER_SECONDS * 1000,
      ).toISOString(),
      hintsRemaining: maxHintsForWord - session.currentWordHintsUsed,
      maxHints: maxHintsForWord,
      revealedLetters,
      currentStreak: session.currentStreak,
      longestStreak: session.longestStreak,
    };
  }
}
