-- V21 Beta Release Candidate Spec §10 "Glyph Economy Production Audit":
-- duplicate reward prevention for the two reward paths inside
-- ProgressionService that have no other claim/idempotency gate of their
-- own (LEVEL_UP glyph bonus, JOURNEY_COMPLETION XP+glyphs) — every other
-- ledger-writing reason legitimately repeats per user (e.g.
-- BOSS_BATTLE_ANSWER once per question answered), so this is a PARTIAL
-- unique index scoped to only these two reasons rather than a blanket
-- constraint on every ledger row. Not expressible in schema.prisma's DSL
-- (partial indexes have no @@unique(..., where: ...) syntax), so this
-- migration is hand-written rather than generated by `prisma migrate
-- diff`. Application-side, ProgressionService.awardXp/awardGlyphs catch
-- the resulting unique-violation and treat it as an idempotent no-op —
-- see their doc comments.
CREATE UNIQUE INDEX "xp_transactions_dedup_level_journey"
  ON "xp_transactions" ("userId", "reason", "reference")
  WHERE "reason" IN ('LEVEL_UP', 'JOURNEY_COMPLETION');

CREATE UNIQUE INDEX "glyph_transactions_dedup_level_journey"
  ON "glyph_transactions" ("userId", "reason", "reference")
  WHERE "reason" IN ('LEVEL_UP', 'JOURNEY_COMPLETION');
