// ISO 3166-1 alpha-2 country code -> continent, mirroring the mobile
// app's src/constants/countries.ts (kept in sync manually -- separate
// TS projects with no shared package). Backs the Continent leaderboard,
// which groups players by the continent their chosen country falls in.
export type Continent =
  | 'Africa'
  | 'Asia'
  | 'Europe'
  | 'North America'
  | 'South America'
  | 'Oceania';

const CONTINENT_BY_COUNTRY_CODE: Record<string, Continent> = {
  DZ: 'Africa',
  AO: 'Africa',
  BJ: 'Africa',
  BW: 'Africa',
  BF: 'Africa',
  BI: 'Africa',
  CV: 'Africa',
  CM: 'Africa',
  CF: 'Africa',
  TD: 'Africa',
  KM: 'Africa',
  CG: 'Africa',
  CD: 'Africa',
  DJ: 'Africa',
  EG: 'Africa',
  GQ: 'Africa',
  ER: 'Africa',
  SZ: 'Africa',
  ET: 'Africa',
  GA: 'Africa',
  GM: 'Africa',
  GH: 'Africa',
  GN: 'Africa',
  GW: 'Africa',
  CI: 'Africa',
  KE: 'Africa',
  LS: 'Africa',
  LR: 'Africa',
  LY: 'Africa',
  MG: 'Africa',
  MW: 'Africa',
  ML: 'Africa',
  MR: 'Africa',
  MU: 'Africa',
  MA: 'Africa',
  MZ: 'Africa',
  NA: 'Africa',
  NE: 'Africa',
  NG: 'Africa',
  RW: 'Africa',
  ST: 'Africa',
  SN: 'Africa',
  SC: 'Africa',
  SL: 'Africa',
  SO: 'Africa',
  ZA: 'Africa',
  SS: 'Africa',
  SD: 'Africa',
  TZ: 'Africa',
  TG: 'Africa',
  TN: 'Africa',
  UG: 'Africa',
  ZM: 'Africa',
  ZW: 'Africa',
  AF: 'Asia',
  AM: 'Asia',
  AZ: 'Asia',
  BH: 'Asia',
  BD: 'Asia',
  BT: 'Asia',
  BN: 'Asia',
  KH: 'Asia',
  CN: 'Asia',
  CY: 'Asia',
  GE: 'Asia',
  IN: 'Asia',
  ID: 'Asia',
  IR: 'Asia',
  IQ: 'Asia',
  IL: 'Asia',
  JP: 'Asia',
  JO: 'Asia',
  KZ: 'Asia',
  KW: 'Asia',
  KG: 'Asia',
  LA: 'Asia',
  LB: 'Asia',
  MY: 'Asia',
  MV: 'Asia',
  MN: 'Asia',
  MM: 'Asia',
  NP: 'Asia',
  KP: 'Asia',
  OM: 'Asia',
  PK: 'Asia',
  PS: 'Asia',
  PH: 'Asia',
  QA: 'Asia',
  SA: 'Asia',
  SG: 'Asia',
  KR: 'Asia',
  LK: 'Asia',
  SY: 'Asia',
  TW: 'Asia',
  TJ: 'Asia',
  TH: 'Asia',
  TL: 'Asia',
  TR: 'Asia',
  TM: 'Asia',
  AE: 'Asia',
  UZ: 'Asia',
  VN: 'Asia',
  YE: 'Asia',
  AL: 'Europe',
  AD: 'Europe',
  AT: 'Europe',
  BY: 'Europe',
  BE: 'Europe',
  BA: 'Europe',
  BG: 'Europe',
  HR: 'Europe',
  CZ: 'Europe',
  DK: 'Europe',
  EE: 'Europe',
  FI: 'Europe',
  FR: 'Europe',
  DE: 'Europe',
  GR: 'Europe',
  HU: 'Europe',
  IS: 'Europe',
  IE: 'Europe',
  IT: 'Europe',
  XK: 'Europe',
  LV: 'Europe',
  LI: 'Europe',
  LT: 'Europe',
  LU: 'Europe',
  MT: 'Europe',
  MD: 'Europe',
  MC: 'Europe',
  ME: 'Europe',
  NL: 'Europe',
  MK: 'Europe',
  NO: 'Europe',
  PL: 'Europe',
  PT: 'Europe',
  RO: 'Europe',
  RU: 'Europe',
  SM: 'Europe',
  RS: 'Europe',
  SK: 'Europe',
  SI: 'Europe',
  ES: 'Europe',
  SE: 'Europe',
  CH: 'Europe',
  UA: 'Europe',
  GB: 'Europe',
  VA: 'Europe',
  AG: 'North America',
  BS: 'North America',
  BB: 'North America',
  BZ: 'North America',
  CA: 'North America',
  CR: 'North America',
  CU: 'North America',
  DM: 'North America',
  DO: 'North America',
  SV: 'North America',
  GD: 'North America',
  GT: 'North America',
  HT: 'North America',
  HN: 'North America',
  JM: 'North America',
  MX: 'North America',
  NI: 'North America',
  PA: 'North America',
  KN: 'North America',
  LC: 'North America',
  VC: 'North America',
  TT: 'North America',
  US: 'North America',
  AR: 'South America',
  BO: 'South America',
  BR: 'South America',
  CL: 'South America',
  CO: 'South America',
  EC: 'South America',
  GY: 'South America',
  PY: 'South America',
  PE: 'South America',
  SR: 'South America',
  UY: 'South America',
  VE: 'South America',
  AU: 'Oceania',
  FJ: 'Oceania',
  KI: 'Oceania',
  MH: 'Oceania',
  FM: 'Oceania',
  NR: 'Oceania',
  NZ: 'Oceania',
  PW: 'Oceania',
  PG: 'Oceania',
  WS: 'Oceania',
  SB: 'Oceania',
  TO: 'Oceania',
  TV: 'Oceania',
  VU: 'Oceania',
};

export function continentForCountryCode(countryCode: string | null | undefined): Continent | null {
  if (!countryCode) return null;
  return CONTINENT_BY_COUNTRY_CODE[countryCode.toUpperCase()] ?? null;
}

/** Every ISO country code that falls in the given continent -- used to scope the Continent leaderboard query. */
export function countryCodesForContinent(continent: Continent): string[] {
  return Object.entries(CONTINENT_BY_COUNTRY_CODE)
    .filter(([, c]) => c === continent)
    .map(([code]) => code);
}

